"""3 IDA Integration tools — symbol import, offset sync, headless scripting."""
import os
import json
import subprocess
from pathlib import Path
from src.shared import PROJECT_ROOT

IDA_DIR = PROJECT_ROOT / "ida_scripts"
IDA_DIR.mkdir(exist_ok=True)

def register(mcp):

    @mcp.tool()
    def ida_import_symbols(input_file: str) -> str:
        """Load IDA-exported symbols (CSV) into the offset database. Args: path to IDA symbol export."""
        if not os.path.isfile(input_file):
            return f"ERROR: file not found: {input_file}"
        from src.tools_database import _binary_hash, _load_db, _save_db
        imported = 0
        db = None
        try:
            with open(input_file) as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith(";") or line.startswith("#") or line.startswith("Name"):
                        continue
                    parts = line.split(",")
                    if len(parts) >= 2:
                        name = parts[0].strip().strip('"')
                        try:
                            addr = parts[1].strip().strip('"')
                            int(addr, 16)
                        except ValueError:
                            addr = parts[1].strip()
                        if db is None:
                            hint_path = next((p for p in PROJECT_ROOT.glob("libs/*.so") if p.exists()), None)
                            bhash = _binary_hash(str(hint_path)) if hint_path else "imported"
                            db = _load_db(bhash)
                            db["source"] = f"ida_import:{input_file}"
                        db["offsets"][name] = {"offset": addr, "notes": "imported from IDA", "binary": str(hint_path or "")}
                        imported += 1
            if db:
                _save_db(db)
                return json.dumps({"source": input_file, "imported": imported, "hash": db["hash"]}, indent=2)
            return "No symbols found in file"
        except Exception as e:
            return f"ERROR: {e}"

    @mcp.tool()
    def ida_sync_offsets(offset_json: str = "") -> str:
        """Generate IDAPython script to apply confirmed offsets back into IDA. Args: offset_json (optional JSON string)."""
        script = """# IDAPython script generated by droid-re-chain
# Apply confirmed offsets as IDA comments/bookmarks
import idautils
import idaapi
import idc

offsets = %s

for name, info in offsets.items():
    try:
        addr = int(info.get('offset', '0'), 16)
        if addr == 0:
            continue
        idc.set_name(addr, name, idc.SN_FORCE)
        idc.add_extra_cmt(addr, True, "droid-re-chain: " + info.get('notes', ''))
        idc.set_bookmark(addr, 0, 0, 0, name, 0)
        print(f"Synced: {name} @ 0x{addr:x}")
    except Exception as e:
        print(f"Failed: {name}: {e}")

print(f"Synced {len(offsets)} offsets")
"""
        if offset_json:
            try:
                parsed = json.loads(offset_json)
                offsets = parsed if isinstance(parsed, dict) else parsed.get("offsets", {})
            except json.JSONDecodeError:
                offsets = {}
        else:
            from src.tools_database import DB_DIR
            offsets = {}
            for f in sorted(DB_DIR.glob("*.json")):
                try:
                    db = json.loads(f.read_text())
                    offsets.update(db.get("offsets", {}))
                except Exception:
                    pass
        filled = script % json.dumps(offsets, indent=4)
        out = IDA_DIR / "sync_offsets.py"
        out.write_text(filled)
        return json.dumps({"script": str(out), "offsets_count": len(offsets),
                           "note": "Run in IDA: File > Script File... or Alt+F7"}, indent=2)

    @mcp.tool()
    def ida_run_script(script_path: str = "") -> str:
        """Attempt to execute an IDAPython script headlessly (requires IDA CLI). Args: script_path."""
        if not script_path:
            available = [str(f.relative_to(PROJECT_ROOT)) for f in IDA_DIR.glob("*.py")]
            return f"Available scripts:\n" + "\n".join(available) if available else "No IDAPython scripts found in ida_scripts/."
        if not os.path.isfile(script_path):
            return f"ERROR: script not found: {script_path}"
        ida_path = os.environ.get("IDA_PATH", "/Applications/IDA Professional 9.0/ida64.app/Contents/MacOS/ida64")
        if not os.path.isfile(ida_path):
            return f"IDA not found at {ida_path}. Set IDA_PATH env var. Script saved at {script_path} for manual run."
        cmd = [ida_path, "-A", f"-S{script_path}", "-"]
        try:
            r = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
            return json.dumps({"script": script_path, "exit_code": r.returncode,
                               "stdout": r.stdout.strip()[:1000], "stderr": r.stderr.strip()[:500]}, indent=2)
        except subprocess.TimeoutExpired:
            return json.dumps({"script": script_path, "error": "timed out after 120s"}, indent=2)
        except FileNotFoundError:
            return f"IDA binary not found at {ida_path}"